"""create the constituency table

Revision ID: 453aef5c78aa
Revises: cfa823e6cc5f
Create Date: 2021-10-04 16:25:08.441483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453aef5c78aa'
down_revision = 'cfa823e6cc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constituency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('parliament_period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parliament_period_id'], ['parliament_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('topic')
    op.drop_table('committee_has_topics')
    op.drop_table('committee')
    op.drop_constraint('parliament_current_project_id_fkey', 'parliament', type_='foreignkey')
    op.drop_column('parliament', 'current_project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parliament', sa.Column('current_project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('parliament_current_project_id_fkey', 'parliament', 'parliament_period', ['current_project_id'], ['id'])
    op.create_table('committee',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('field_legislature_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='committee_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('committee_has_topics',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('committee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], name='committee_has_topics_committee_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='committee_has_topics_topic_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='committee_has_topics_pkey')
    )
    op.create_table('topic',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('api_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('abgeordnetenwatch_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent'], ['topic.id'], name='topic_parent_fkey'),
    sa.PrimaryKeyConstraint('id', name='topic_pkey')
    )
    op.drop_table('constituency')
    # ### end Alembic commands ###
